### ISSUE TITLE
parameters table

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-db#11]
in the updated schema lets drop the following columns:

`is_core` 
`max_color_value`

We are no longer using these value so they shouldnt be needed moving forward

**Comment by caparker** [comment]
Done.
I'm thinking it could be helpful to add some sort of classifier to the measurands table. Examples would be `particulate`, `meteorological` , `toxin` etc. Not well thought out at this point but I can see its usefulness as a query parameter or something for the map.

**Comment by russbiggs** [comment]
this would be really nice, it would help break out different parameters more easily especially as we increase the diversity with meteorological parameters.

**Comment by caparker** [comment]
If we come up with a list it should be straightforward. Then we could just add it to the parameters model.

**Comment by russbiggs** [comment]
I like the idea of separating out `particulate`, `toxin` instead of `pollutant`. Would something like `gaseous` be an one or do those fit into `toxin`?
