### ISSUE TITLE
Mobile tiles generalization 

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-db#5]
Currently generating the generalized mobile tiles is quite expensive and requires refreshing materialized views. I'm wondering if theres ways in the new schema we can make this process more efficient and avoid the cron based complete refreshing of materialized views to accomplish a similar result. 

Currently the mat views that do this are here: 
https://github.com/openaq/openaq-db/blob/main/openaqdb/idempotent/static_summaries.sql#L5

For a single sensor_node this takes about 30s to update. I'm wondering if we can do something similar to how we are doing sensors_latest, updating a a table only if relevant data comes in.

Also curious if a GiST index instead of a BRiN on the measurements lat,long field could help with some of these spatial processes.
https://github.com/openaq/openaq-db/blob/6a4f3ecb15002c1aca2a6801a901ee2abdbeb375/openaqdb/tables/measurements.sql#L13

@caparker

**Comment by russbiggs** [comment]
reading more on the BRiN vs GiST question, insert speeds are much faster for BRiN, which could be an issue given its on the measurements table

**Comment by caparker** [comment]
Could you point me to the tiles data model so I can see what fields we need. I am thinking we should avoid the measurements table altogether

**Comment by russbiggs** [comment]
I think there will need to be a different model for the generalized mobile tiles (only at low zoom level) and the full mobile tiles (only at high zoom). We haven't fulled spec'd out the generalized but I think they should just need:

* sensor_nodes_id 
* measurand
* some sort of generalize geometry (this is the current challenge)


Whereas full mobile tiles we'll want

* sensor_nodes_id 
* measurand
* lat
* lon
* datetime 
* value
